### ISSUE TITLE
Home assistant integration

### ISSUE THREAD

**Issue by cunninr2** [Ankermgmt/ankermake-m5-protocol#130]
Your issue may already be reported! Please search on the [issue tracker](https://github.com/Ankermgmt/ankermake-m5-protocol/issues) before creating one.

**Describe the solution you'd like**
Excellent work.  I'm really interested in getting status monitoring of the Ankermake M5  into home assistant so I can monitor from afar and auto shutdown.  Probably only needs a few status parameters such as printing, job completed, bed/nozzle temps. start/stop printing.  The icing on the cake would be a camera feed for sure. keep up the good work.

**Describe alternatives you've considered**

**Additional context**

**Comment by BowlesCR** [comment]
Despite the title, #92 seems to be working in this same direction -- you may want to see about coordinating efforts.

**Comment by Phoenix-DH** [comment]
I would also be ninteressted in a HA integration.
Thanks ✌🏻

**Comment by JayRHa** [comment]
Please work on this#

**Comment by sondregronas** [comment]
Hi - I've been working on a Home Assistant integration that seems to have now reached a usable stage, which is available here: https://github.com/sondregronas/ankermake-hass-component and can be installed via hacs.

Note: I've only tested with ankerctl in the v1.1 branch, and I'm not sure how stable it is yet as finding errors or debugging takes a lot of time

I'm also open to moving said integration over to the Ankermgmt organization if it's of any interest. (https://github.com/Ankermgmt/ankermgmt-hassio-addons/issues/5)

**Comment by Phoenix-DH** [comment]
Hey,
this sounds great! Thanks.
Does that mean that in addition to your hacs also an ankerctl instance must be running? Anything else needrd on HA? MQTT Broker?

But where to find ankerctl for HA? Am I blind?

Thanks

—

Addon found 👍🏻

**Comment by sondregronas** [comment]
You just need an instance of ankerctl running, yes. Once you've installed via HACS / imported to `custom_components` you should find it under "Add Integration" in the `Devices & Services` dashboard. There's no need for an MQTT broker or any other dependencies as it uses ankerctl's own provided webserver (`/ws/mqtt` endpoint)

![image](https://github.com/Ankermgmt/ankermake-m5-protocol/assets/44143748/c87a6b7d-0ec6-4534-a51c-159e85e8d718)

**Comment by Phoenix-DH** [comment]
Thanks!
Just added your repo to HACS and the Addon to HA.
Will try next time when I use the printer.

Thanks.

**Comment by Phoenix-DH** [comment]
Is the current way to install home assistant addon.
Afterwards install ankerctl on your pc to generste login.json.
Import login.json on the home assistant ankerctl webpage?

**Comment by sondregronas** [comment]
You need ankerctl running, I use this fork in docker for the time being: https://github.com/sondregronas/ankermake-m5-protocol/tree/patch-exiles-1.1-auto-restart-on-failure, but I presume the home assistant version should work.

The integration only needs the URL of an ankerctl instance, it doesn't matter if its running via home assistant or not.

EDIT: This `docker-compose.yml` file should work with my changes, though there's not much deviation from this default branch for the integration if you don't use go2rtc for the camera

```yaml
services:
    ankerctl:
        container_name: ankerctl
        restart: unless-stopped
        build: 
          context: https://github.com/sondregronas/ankermake-m5-protocol.git#patch-exiles-1.1-auto-restart-on-failure
        privileged: true
        # host-mode networking is required for pppp communication with the
        # printer, since it is an asymmetrical udp protocol.
        network_mode: host
        environment:
            - FLASK_HOST=0.0.0.0
            - FLASK_PORT=4470
        volumes:
            - ankerctl_vol:/root/.config/ankerctl
            - ./ankermake-m5-protocol/web/:/app/web

    # This container will restart the ankerctl container every 2 hours
    # as a temporary workaround for some socket issues.
    ankerctl_restarter:
      image: docker
      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
      # 2 hours = 7200 seconds
      command: ["/bin/sh", "-c", "while true; do sleep 7200; docker restart ankerctl; done"]
      restart: unless-stopped
volumes:
    ankerctl_vol:
```
